// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: "mongodb+srv://cindybarria2_db_user:dsNPSpwyrz42IgtB@cluster0.0izvyag.mongodb.net/dia6"
  }
});
